services:
  db:
    container_name: bep_db
    image: postgres:16.2
    ports:
      - "15432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bep
      POSTGRES_USER: bep
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "bep", "-d", "bep"]
      interval: 2s
      retries: 120

  nginx:
    container_name: bep_nginx
    image: nginx:1.25
    volumes:
      # config
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      # mount app media and static content
      - .data/media:/media:ro
      # - .data/static:/static:ro # do not mount in development mode
    ports:
      - "8080:80"
    depends_on:
      app:
        condition: service_healthy

  app:
    container_name: bep_app
    # image: dhil/bep
    build:
      context: .
      target: bep
    ports:
      - "8888:80"
    volumes:
      # code for development
      - .:/app

      # files uploads
      - .data/media:/media

      # # persist static outside of container so it can be shared with nginx
      # - .data/static:/app/static # do not mount in development mode
      # use the container's node_modules folders (don't override with local dev)
      - /app/node_modules
    environment:
      DEBUG: True
      DB_HOST: db
      DB_NAME: bep
      DB_USER: bep
      DB_PASSWORD: password
      EMAIL_HOST: mail
      EMAIL_HOST_USER: bep
      EMAIL_HOST_PASSWORD: password
      MEDIA_FOLDER_UID: 101
      MEDIA_FOLDER_GID: 101
      GUNICORN_RELOAD: True
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/health_check/ || exit 1"]
      interval: 2s
      retries: 120
    depends_on:
      db:
        condition: service_healthy

  mail:
    container_name: bep_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"