# Generated by Django 5.1.5 on 2025-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injunction',
            name='uniform_title',
            field=models.TextField(blank=True),
        ),
    ]
