# Generated by Django 5.1.7 on 2025-05-29 22:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0002_alter_injunction_uniform_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='geom_post_1541',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Post 1541 Geom'),
        ),
        migrations.AddField(
            model_name='diocese',
            name='geom_pre_1541',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Pre 1541 Geom'),
        ),
    ]
