# Generated by Django 5.2.3 on 2025-06-23 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0003_diocese_geom_post_1541_diocese_geom_pre_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='geom_point',
            field=django.contrib.gis.db.models.fields.PointField(verbose_name='Geo Point', blank=True, geography=True, null=True, srid=4326),
        ),
    ]
