# Generated by Django 5.2.3 on 2025-06-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0004_parish_geom_point'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                UPDATE bep_parish
                SET "geom_point" = ST_SetSRID(ST_MakePoint("longitude", "latitude"), 4326)
                WHERE "longitude" IS NOT NULL
                AND "latitude" IS NOT NULL;
            ''',
            reverse_sql='''
                UPDATE bep_parish
                SET "longitude" = ST_X("geom_point"::geometry),
                    "latitude" = ST_Y("geom_point"::geometry)
                WHERE "geom_point" IS NOT NULL;
            ''',
            )
    ]

