# Generated by Django 5.2.3 on 2025-06-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0005_populate_parish_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parish',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='longitude',
        ),
    ]
