# Generated by Django 6.0.1 on 2026-02-26 23:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0006_remove_parish_latitude_remove_parish_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('label', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('description', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddField(
            model_name='diocese',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('label', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('description', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddField(
            model_name='transaction',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('id', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector(django.db.models.functions.text.LPad(django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), 5, models.Value('0')), config='english', weight='A'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('transcription', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('modern_transcription', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('public_notes', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('location', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='county',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='bep_county_search__db2373_gin'),
        ),
        migrations.AddIndex(
            model_name='diocese',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='bep_diocese_search__b05575_gin'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='bep_transac_search__7e4daa_gin'),
        ),
    ]
