# Generated by Django 6.0.3 on 2026-05-01 21:41

import bep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0007_county_search_vector_diocese_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bep_transaction_action',
            },
        ),
        migrations.CreateModel(
            name='TransactionMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bep_transaction_medium',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=True, verbose_name='Is expense?', help_text='Check for expense/cost/disposal/etc or uncheck for income/dotation/etc'),
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='bep_book_search__32c3ed_gin',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='uniform_title',
            new_name='full_title',
        ),
        migrations.RenameField(
            model_name='injunction',
            old_name='uniform_title',
            new_name='full_title',
        ),
        migrations.AlterField(
            model_name='book',
            name='variant_titles',
            field=bep.models.VariantNamesArrayField(base_field=models.CharField(), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='injunction',
            name='variant_titles',
            field=bep.models.VariantNamesArrayField(base_field=models.CharField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_actions',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='bep.transactionaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_mediums',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='bep.transactionmedium'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='search_vector',
        ),
    ]
