# Generated by Django 6.0.3 on 2026-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0008_transactionaction_transactionmedium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='written_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='written_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='written_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='end_date',
        ),
        migrations.AddField(
            model_name='holding',
            name='reference_number',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='sort_year',
            field=models.IntegerField(blank=True, help_text='Enter the year for sorting. For "unknown" dates leave blank (do not use zero or a placeholder). For uncertain dates (ex: "c. 1560-61") or ranges (ex: "1560-70") use the earliest year (ex: 1560).', null=True),
        ),
        migrations.AddField(
            model_name='injunction',
            name='sort_year',
            field=models.IntegerField(blank=True, help_text='Enter the year for sorting. For "unknown" dates leave blank (do not use zero or a placeholder). For uncertain dates (ex: "c. 1560-61") or ranges (ex: "1560-70") use the earliest year (ex: 1560).', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sort_year',
            field=models.IntegerField(blank=True, help_text='Enter the year for sorting. For "unknown" dates leave blank (do not use zero or a placeholder). For uncertain dates (ex: "c. 1560-61") or ranges (ex: "1560-70") use the earliest year (ex: 1560).', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sort_year',
            field=models.IntegerField(blank=True, help_text='Enter the year for sorting. For "unknown" dates leave blank (do not use zero or a placeholder). For uncertain dates (ex: "c. 1560-61") or ranges (ex: "1560-70") use the earliest year (ex: 1560).', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='full_title',
            field=models.TextField(blank=True),
        ),
    ]
