# Generated by Django 6.0.3 on 2026-04-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0010_book_search_vector_book_bep_book_search__32c3ed_gin'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE bep_transaction SET start_date = NULL WHERE EXTRACT(YEAR FROM start_date) <= 1500"
        ),
        migrations.RunSQL(
            "UPDATE bep_transaction SET end_date = NULL WHERE EXTRACT(YEAR FROM end_date) <= 1500"
        ),
        migrations.RunSQL(
            "UPDATE bep_inventory SET start_date = NULL WHERE EXTRACT(YEAR FROM start_date) <= 1500"
        ),
        migrations.RunSQL(
            "UPDATE bep_inventory SET end_date = NULL WHERE EXTRACT(YEAR FROM end_date) <= 1500"
        ),
        migrations.RunSQL(
            "UPDATE bep_monarch SET start_date = NULL WHERE EXTRACT(YEAR FROM start_date) <= 1500"
        ),
        migrations.RunSQL(
            "UPDATE bep_monarch SET end_date = NULL WHERE EXTRACT(YEAR FROM end_date) <= 1500"
        ),
    ]
