# Generated by Django 6.0.3 on 2026-04-29 20:48

from django.db import migrations

# from bep.models import TransactionAction, Transaction, TransactionMedium

def populate_data(apps, schema_editor):
    Transaction = apps.get_model('bep', 'Transaction')
    TransactionMedium = apps.get_model('bep', 'TransactionMedium')
    TransactionAction = apps.get_model('bep', 'TransactionAction')
    if Transaction and TransactionMedium and TransactionAction:
        # actions
        purchase_action = TransactionAction.objects.create(label='Purchase')
        bossing_action = TransactionAction.objects.create(label='Bossing')
        binding_action = TransactionAction.objects.create(label='Binding')
        clasping_action = TransactionAction.objects.create(label='Clasping')
        covering_action = TransactionAction.objects.create(label='Covering')
        carriage_action = TransactionAction.objects.create(label='Carriage')
        repairing_action = TransactionAction.objects.create(label='Repairing')
        exchange_action = TransactionAction.objects.create(label='Exchange')
        manufacture_action = TransactionAction.objects.create(label='Manufacture')
        writing_action = TransactionAction.objects.create(label='Writing')
        certifying_purchase_action = TransactionAction.objects.create(label='Certifying Purchase')
        payment_action = TransactionAction.objects.create(label='Payment')
        destruction_action = TransactionAction.objects.create(label='Destruction')
        miscellaneous_action = TransactionAction.objects.create(label='Miscellaneous Costs')
        sale_action = TransactionAction.objects.create(label='Sale')
        donation_gifting_or_disposal_action = TransactionAction.objects.create(label='Donation, Gifting, or Disposal')
        record_of_missing_action = TransactionAction.objects.create(label='Record of Missing')
        record_of_ownership_action = TransactionAction.objects.create(label='Record of Ownership')

        # mediums
        book_medium = TransactionMedium.objects.create(label='Book')
        paper_book_medium = TransactionMedium.objects.create(label='Paper Book')
        printed_book_medium = TransactionMedium.objects.create(label='Printed Book')
        book_of_orders_medium = TransactionMedium.objects.create(label='Book of Orders')
        book_of_prayer_medium = TransactionMedium.objects.create(label='Book of Prayers')
        book_of_common_prayer_medium = TransactionMedium.objects.create(label='Book of Common Prayer')
        book_of_psalms_medium = TransactionMedium.objects.create(label='Book of Psalms')
        book_of_canons_medium = TransactionMedium.objects.create(label='Book of Canons')
        book_of_thanksgiving_medium = TransactionMedium.objects.create(label='Book of Thanksgiving')
        book_of_martyrs_medium = TransactionMedium.objects.create(label='Book of Martyrs')
        book_of_constitutions_medium = TransactionMedium.objects.create(label='Book of Constitutions')
        book_for_fasting_medium = TransactionMedium.objects.create(label='Book for Fasting')
        communion_book_medium = TransactionMedium.objects.create(label='Communion Book')
        bible_medium = TransactionMedium.objects.create(label='Bible')
        mass_book_medium = TransactionMedium.objects.create(label='Mass Book')
        chains_for_book_medium = TransactionMedium.objects.create(label='Chain(s) for Book')
        venite_book_medium = TransactionMedium.objects.create(label='Venite Book')
        music_book_medium = TransactionMedium.objects.create(label='Music Book')
        service_book_medium = TransactionMedium.objects.create(label='Service Book')
        record_book_medium = TransactionMedium.objects.create(label='Record Book')
        proclamation_medium = TransactionMedium.objects.create(label='Proclamation', description='<p>Proclamation between 1536 and 1642</p>')
        furniture_medium = TransactionMedium.objects.create(label='Furniture', description='<p>Used for books</p>')
        desk_or_lecterns_medium = TransactionMedium.objects.create(label='Desk or Lectern')
        injunction_medium = TransactionMedium.objects.create(label='Injunction')
        homilies_medium = TransactionMedium.objects.create(label='Homilies')
        acts_of_parliament_medium = TransactionMedium.objects.create(label='Acts of Parliament')
        articles_medium = TransactionMedium.objects.create(label='Articles')
        erasmus_paraphrases_medium = TransactionMedium.objects.create(label='Erasmus Paraphrases')
        book_hardware_medium = TransactionMedium.objects.create(label='Book Hardware', description='<p>Bosses, clasps etc.</p>')
        royal_declaration_or_decree_medium = TransactionMedium.objects.create(label='Royal Declaration or Decree')
        statute_medium = TransactionMedium.objects.create(label='Statute')
        order_or_precept_medium = TransactionMedium.objects.create(label='Order or Precept')
        bishop_jewells_works_medium = TransactionMedium.objects.create(label='Bishop Jewells Works')
        book_by_jewell_and_harding_medium = TransactionMedium.objects.create(label='Book by Jewell and Harding')
        table_of_degrees_medium = TransactionMedium.objects.create(label='Table of Degrees')
        table_of_commandments_medium = TransactionMedium.objects.create(label='Table of Commandments')
        printed_sheet_medium = TransactionMedium.objects.create(label='Printed Sheet')
        almanac_medium = TransactionMedium.objects.create(label='Almanac')
        processional_medium = TransactionMedium.objects.create(label='Processional')
        stationery_medium = TransactionMedium.objects.create(label='Stationery')
        catechism_medium = TransactionMedium.objects.create(label='Catechism')
        manual_medium = TransactionMedium.objects.create(label='Manual')
        calendar_medium = TransactionMedium.objects.create(label='Calendar')
        song_medium = TransactionMedium.objects.create(label='Song')
        hymnal_medium = TransactionMedium.objects.create(label='Hymnal')
        letter_medium = TransactionMedium.objects.create(label='Letter')
        bill_medium = TransactionMedium.objects.create(label='Bill')
        fine_medium = TransactionMedium.objects.create(label='Fine')
        church_rate_medium = TransactionMedium.objects.create(label='Church Rate')
        script_text_painted_medium = TransactionMedium.objects.create(label='Script/Text Painted')
        prayer_medium = TransactionMedium.objects.create(label='Prayer')
        register_medium = TransactionMedium.objects.create(label='Register')
        antiphoner_medium = TransactionMedium.objects.create(label='Antiphoner')
        grail_medium = TransactionMedium.objects.create(label='Grail')
        legend_medium = TransactionMedium.objects.create(label='Legend')
        to_review_medium = TransactionMedium.objects.create(label='To Review', description='<p>Temporary</p>')

        transaction_category_map = {
            # 1, Bossing a Book or Books
            1: {'action': bossing_action, 'mediums': [book_medium], 'is_expense': True},

            # 2, Purchase of a Proclamation
            2: {'action': purchase_action, 'mediums': [proclamation_medium], 'is_expense': True},

            # 3, Purchase of a Book of Prayers
            3: {'action': purchase_action, 'mediums': [book_medium, book_of_prayer_medium], 'is_expense': True},

            # 4, Purchase of a Paper Book
            4: {'action': purchase_action, 'mediums': [book_medium, paper_book_medium], 'is_expense': True},

            # 5, Carriage of a Book or Books
            5: {'action': carriage_action, 'mediums': [book_medium], 'is_expense': True},

            # 6, Purchase of Desks or Lecterns
            6: {'action': purchase_action, 'mediums': [desk_or_lecterns_medium, furniture_medium], 'is_expense': True},

            # 7, Repairing a Book or Books
            7: {'action': repairing_action, 'mediums': [book_medium], 'is_expense': True},

            # 8, Purchase of a Music Book or Books
            8: {'action': purchase_action, 'mediums': [book_medium, music_book_medium], 'is_expense': True},

            # 10, Listing Books Owned by the Parish
            10: {'action': record_of_ownership_action, 'mediums': [book_medium]},

            # 11, Sale of a Book or Books
            11: {'action': sale_action, 'mediums': [book_medium], 'is_expense': False},

            # 12, Recording a Missing Book or Books
            12: {'action': record_of_missing_action, 'mediums': [book_medium]},

            # 15, Purchase of a Liturgical Work, Queen Mary
            15: {'action': purchase_action, 'mediums': [book_of_prayer_medium], 'is_expense': True},

            # 16, Record of Ownership
            16: {'action': record_of_ownership_action, 'mediums': [], 'is_expense': True},

            # 17, Purchase of Injunctions
            17: {'action': purchase_action, 'mediums': [injunction_medium], 'is_expense': True},

            # 18, Binding a Book or Books
            18: {'action': binding_action, 'mediums': [book_medium], 'is_expense': True},

            # 19, Purchase of Homilies
            19: {'action': purchase_action, 'mediums': [homilies_medium], 'is_expense': True},

            # 20, Purchase of a Printed Book or Books
            20: {'action': purchase_action, 'mediums': [printed_book_medium, book_medium], 'is_expense': True},

            # 21, Purchase of Chain(s) for Book(s)
            21: {'action': purchase_action, 'mediums': [chains_for_book_medium], 'is_expense': True},

            # 22, Purchase of a Bible
            22: {'action': purchase_action, 'mediums': [bible_medium, book_medium], 'is_expense': True},

            # 23, Purchase of a Book of Orders
            23: {'action': purchase_action, 'mediums': [book_of_orders_medium, book_medium], 'is_expense': True},

            # 24, Sale of Furniture (used for books)
            24: {'action': sale_action, 'mediums': [furniture_medium], 'is_expense': False},

            # 25, Purchase of Furniture (used for books)
            25: {'action': purchase_action, 'mediums': [furniture_medium], 'is_expense': True},

            # 26, Purchase of Service Book
            26: {'action': purchase_action, 'mediums': [service_book_medium, book_medium], 'is_expense': True},

            # 27, Purchase of Record Book
            27: {'action': purchase_action, 'mediums': [record_book_medium, book_medium], 'is_expense': True},

            # 29, Acts of Parliament
            29: {'action': purchase_action, 'mediums': [acts_of_parliament_medium], 'is_expense': True},

            # 30, Purchase of Psalters
            30: {'action': purchase_action, 'mediums': [book_of_psalms_medium, book_medium], 'is_expense': True},

            # 31, Purchase of Articles
            31: {'action': purchase_action, 'mediums': [articles_medium], 'is_expense': True},

            # 34, Purchase of Erasmus Paraphrases
            34: {'action': purchase_action, 'mediums': [erasmus_paraphrases_medium], 'is_expense': True},

            # 35, Purchase of a Communion Book
            35: {'action': purchase_action, 'mediums': [communion_book_medium, book_medium], 'is_expense': True},

            # 36, Purchase of Book Hardware (Bosses, clasps etc.)
            36: {'action': purchase_action, 'mediums': [book_hardware_medium], 'is_expense': True},

            # 37, Repairing Furniture Used for Books
            37: {'action': repairing_action, 'mediums': [furniture_medium], 'is_expense': True},

            # 38, Purchase of a Royal Declaration or Decree
            38: {'action': purchase_action, 'mediums': [royal_declaration_or_decree_medium], 'is_expense': True},

            # 39, Purchase of Book of Canons
            39: {'action': purchase_action, 'mediums': [book_of_canons_medium, book_medium], 'is_expense': True},

            # 41, Gifting or disposal of Books
            41: {'action': donation_gifting_or_disposal_action, 'mediums': [book_medium], 'is_expense': False},

            # 42, Purchase of a Statute
            42: {'action': purchase_action, 'mediums': [statute_medium], 'is_expense': True},

            # 45, Carriage of an Order or Precept
            45: {'action': carriage_action, 'mediums': [order_or_precept_medium], 'is_expense': True},

            # 46, Miscellaneous
            46: {'action': miscellaneous_action, 'mediums': [], 'is_expense': True},

            # 47, Purchase of Bishop Jewells Works
            47: {'action': purchase_action, 'mediums': [bishop_jewells_works_medium], 'is_expense': True},

            # 48, To Review (Temporary Category)
            48: {'action': None, 'mediums': [to_review_medium]},

            # 49, Carriage of a Proclamation
            49: {'action': carriage_action, 'mediums': [proclamation_medium], 'is_expense': True},

            # 50, Carriage of a Book of Prayers
            50: {'action': carriage_action, 'mediums': [book_of_prayer_medium, book_medium], 'is_expense': True},

            # 51, Destruction of Books
            51: {'action': destruction_action, 'mediums': [book_medium], 'is_expense': True},

            # 52, Purchase of a Table of Degrees
            52: {'action': purchase_action, 'mediums': [table_of_degrees_medium], 'is_expense': True},

            # 53, Purchase of a Printed Sheet
            53: {'action': purchase_action, 'mediums': [printed_sheet_medium], 'is_expense': True},

            # 54, Carriage of Injunctions
            54: {'action': carriage_action, 'mediums': [injunction_medium], 'is_expense': True},

            # 55, Purchase of a Book of Psalms
            55: {'action': purchase_action, 'mediums': [book_of_psalms_medium, book_medium], 'is_expense': True},

            # 56, Purchase of an Almanac
            56: {'action': purchase_action, 'mediums': [almanac_medium], 'is_expense': True},

            # 57, Exchange of a Book
            57: {'action': exchange_action, 'mediums': [book_medium], 'is_expense': True},

            # 58, Purchase of a Processional
            58: {'action': purchase_action, 'mediums': [processional_medium], 'is_expense': True},

            # 59, Purchase of a Book of Common Prayer
            59: {'action': purchase_action, 'mediums': [book_of_common_prayer_medium, book_of_prayer_medium, book_medium], 'is_expense': True},

            # 60, Purchase of Stationery
            60: {'action': purchase_action, 'mediums': [stationery_medium], 'is_expense': True},

            # 61, Purchase of a Book for Fasting
            61: {'action': purchase_action, 'mediums': [book_for_fasting_medium, book_medium], 'is_expense': True},

            # 63, Certifying the Purchase of a Book
            63: {'action': certifying_purchase_action, 'mediums': [book_medium], 'is_expense': True},

            # 64, Purchase of Book of Thanksgiving
            64: {'action': purchase_action, 'mediums': [book_of_thanksgiving_medium, book_medium], 'is_expense': True},

            # 66, Purchase of a Book by Jewell and Harding
            66: {'action': purchase_action, 'mediums': [book_by_jewell_and_harding_medium, book_medium], 'is_expense': True},

            # 67, Purchase of a Table of Commandments
            67: {'action': purchase_action, 'mediums': [table_of_commandments_medium], 'is_expense': True},

            # 68, Purchase of a Catechism
            68: {'action': purchase_action, 'mediums': [catechism_medium], 'is_expense': True},

            # 69, Purchase of a Book of Martyrs
            69: {'action': purchase_action, 'mediums': [book_of_martyrs_medium, book_medium], 'is_expense': True},

            # 70, Purchase of a Mass Book
            70: {'action': purchase_action, 'mediums': [mass_book_medium, book_medium], 'is_expense': True},

            # 71, Purchase of a Manual
            71: {'action': purchase_action, 'mediums': [manual_medium], 'is_expense': True},

            # 72, Purchase of a Calendar
            72: {'action': purchase_action, 'mediums': [calendar_medium], 'is_expense': True},

            # 73, Writing of an Account or Book
            73: {'action': writing_action, 'mediums': [], 'is_expense': True},

            # 74, Covering a Book or Books
            74: {'action': covering_action, 'mediums': [book_medium], 'is_expense': True},

            # 75, Manufacture of a Book or Books
            75: {'action': manufacture_action, 'mediums': [book_medium], 'is_expense': True},

            # 76, Delivery of a Book or Books
            76: {'action': carriage_action, 'mediums': [book_medium], 'is_expense': True},

            # 77, Purchase of a song or songs
            77: {'action': purchase_action, 'mediums': [song_medium], 'is_expense': True},

            # 78, Payment of a Fine Related to Books
            78: {'action': payment_action, 'mediums': [fine_medium], 'is_expense': True},

            # 79, Carriage of a Letter
            79: {'action': carriage_action, 'mediums': [letter_medium], 'is_expense': True},

            # 80, Writing or Laying in of a Bill
            80: {'action': writing_action, 'mediums': [bill_medium], 'is_expense': True},

            # 81, Purchase of a Prayer (Printed Sheet)
            81: {'action': purchase_action, 'mediums': [prayer_medium, printed_sheet_medium], 'is_expense': True},

            # 82, Carriage of a Prayer
            82: {'action': carriage_action, 'mediums': [prayer_medium], 'is_expense': True},

            # 83, Payment for a Church Rate
            83: {'action': payment_action, 'mediums': [church_rate_medium], 'is_expense': True},

            # 84, Payment for Script/Text Painted
            84: {'action': payment_action, 'mediums': [script_text_painted_medium], 'is_expense': True},

            # 85, Purchase of a register
            85: {'action': purchase_action, 'mediums': [register_medium], 'is_expense': True},

            # 87, Purchase of a Book of Statutes
            87: {'action': purchase_action, 'mediums': [statute_medium, book_medium], 'is_expense': True},

            # 89, Clasping a Book
            89: {'action': clasping_action, 'mediums': [book_medium], 'is_expense': True},

            # 90, Purchase of an Order
            90: {'action': purchase_action, 'mediums': [order_or_precept_medium], 'is_expense': True},

            # 93, Purchase of a hymnal
            93: {'action': purchase_action, 'mediums': [hymnal_medium, song_medium], 'is_expense': True},

            # 95, Purchase of an antiphoner
            95: {'action': purchase_action, 'mediums': [antiphoner_medium, book_medium], 'is_expense': True},

            # 96, Purchase of a grail
            96: {'action': purchase_action, 'mediums': [grail_medium], 'is_expense': True},

            # 97, Purchase of an Abridgement of Statutes
            97: {'action': purchase_action, 'mediums': [statute_medium], 'is_expense': True},

            # 98, Purchase of a Book of Constitutions
            98: {'action': purchase_action, 'mediums': [book_of_constitutions_medium, book_medium], 'is_expense': True},

            # 99, Purchase of a Legend
            99: {'action': purchase_action, 'mediums': [legend_medium], 'is_expense': True},

            # 100, Carriage of Articles
            100: {'action': carriage_action, 'mediums': [articles_medium], 'is_expense': True},

            # 101, Purchase of a Venite book
            101: {'action': purchase_action, 'mediums': [venite_book_medium, book_medium], 'is_expense': True},

            # 103, Receipt of a donation of books or money for books
            103: {'action': donation_gifting_or_disposal_action, 'mediums': [book_medium], 'is_expense': False},
        }

        for transaction in Transaction.objects.prefetch_related('transaction_categories').all().iterator(chunk_size=10):
            actions = []
            mediums = []
            for transaction_category in transaction.transaction_categories.all():
                mapping = transaction_category_map.get(transaction_category.pk)
                if mapping.get('action') and mapping.get('action').pk not in [action.pk for action in actions]:
                    actions.append(mapping.get('action'))
                if mapping.get('mediums') and len(mapping.get('mediums')) > 0:
                    for new_medium in mapping.get('mediums'):
                        if new_medium.pk not in [medium.pk for medium in mediums]:
                            mediums.append(new_medium)
                if mapping.get('is_expense') != None:
                    transaction.is_expense = mapping.get('is_expense')

            transaction.transaction_actions.set(actions)
            transaction.transaction_mediums.set(mediums)
            transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0011_null_unknown_date_placeholders'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
