# Generated by Django 6.0.3 on 2026-05-04 20:38
import calendar
import re
from django.db import migrations

# from bep.models import Holding, Inventory, Transaction, Injunction

def get_uncertain_date_tuple(start_date, end_date):
    uncertain = False

    start_year = start_date.year if start_date else None
    start_month = start_date.month if start_date else None
    start_day = start_date.day if start_date else None
    if start_month == 3 and start_day in (24, 25):
        start_month = None
        start_day = None
        uncertain = True

    end_year = end_date.year if end_date else None
    end_month = end_date.month if end_date else None
    end_day = end_date.day if end_date else None
    if end_month == 3 and end_day in (24, 25):
        end_month = None
        end_day = None
        uncertain = True
    elif start_month != None and start_day != None and end_month == start_month and end_day in [start_day, start_day-1]:
        end_month = None
        end_day = None

    if end_year != None and start_year != None:
        if end_year < start_year:
            end_year = None
            uncertain = True
        elif end_year > start_year:
            uncertain = True

    return (uncertain, start_year, start_month, start_day, end_year, end_month, end_day)

def get_year_range(start_year, end_year):
    if start_year == None:
        return ''
    elif end_year == None or start_year >= end_year:
        return f'{start_year}'
    elif start_year // 100 == end_year // 100:
        return f'{start_year}-{end_year % 100}'
    else:
        return f'{start_year}-{end_year}'

def get_date_str(uncertain, start_year, start_month, start_day, end_year, end_month, end_day):
    if start_year == None:
        return None

    uncertain_str = 'c. ' if uncertain else ''
    if end_year != None and end_year > start_year and start_month != None and end_month != None and start_day != None and end_day != None:
        return f'{uncertain_str}{start_year} {calendar.month_name[start_month]} {start_day} - {end_year} {calendar.month_name[end_month]} {end_day}'

    result = f'{uncertain_str}{get_year_range(start_year, end_year)}'
    if start_month != None:
        result += f' {calendar.month_name[start_month]}'
        if start_day != None:
            result += f' {start_day}'
    return result

def populate_data(apps, schema_editor):
    Holding = apps.get_model('bep', 'Holding')
    Inventory = apps.get_model('bep', 'Inventory')
    Transaction = apps.get_model('bep', 'Transaction')
    Injunction = apps.get_model('bep', 'Injunction')

    for holding in Holding.objects.filter(start_date__isnull=False).all().iterator(chunk_size=100):
        (uncertain, start_year, start_month, start_day, end_year, end_month, end_day) = get_uncertain_date_tuple(holding.start_date, None)
        holding.sort_year = start_year
        if holding.date == None or holding.date == '' and start_year:
            holding.date = get_date_str(uncertain, start_year, start_month, start_day, None, None, None)
        holding.save()

    for inventory in Inventory.objects.filter(start_date__isnull=False).all().iterator(chunk_size=100):
        (uncertain, start_year, start_month, start_day, end_year, end_month, end_day) = get_uncertain_date_tuple(inventory.start_date, inventory.end_date)
        inventory.sort_year = start_year
        if inventory.date == None or inventory.date == '' and start_year:
            inventory.date = get_date_str(uncertain, start_year, start_month, start_day, end_year, end_month, end_day)
        inventory.save()

    for transaction in Transaction.objects.filter(start_date__isnull=False).all().iterator(chunk_size=100):
        (uncertain, start_year, start_month, start_day, end_year, end_month, end_day) = get_uncertain_date_tuple(transaction.start_date, transaction.end_date)
        transaction.sort_year = start_year
        if transaction.date == None or transaction.date == '' and start_year:
            transaction.date = get_date_str(uncertain, start_year, start_month, start_day, end_year, end_month, end_day)
        transaction.save()

    for injunction in Injunction.objects.all().iterator(chunk_size=100):
        if injunction.date:
            years = [int(n) for n in re.findall(r'\d{4}', injunction.date)]
            if len(years) > 0:
                injunction.sort_year = years[0]
                injunction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0012_move_transaction_categories_to_actions_and_mediums'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]