# Generated by Django 6.0.3 on 2026-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0014_auto_filled_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='calendar_year_help_text_override',
            field=models.TextField(blank=True, help_text="Enter the help text describing the Parish's calendar year (if different from the default March 25 - March 24)", null=True),
        ),
    ]
